In [ ]:
import pandas as pd

In [ ]:
# creating a Series from a list
import pandas as pd
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
# create a DataFrame from a dictionary
data = {"a" :1 , "b": 2, "c": 3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
data2 = [1,2,3,4,5]
index = ['a', 'b', 'c', 'd', 'e']
series_index = pd.Series(data2, index=index)
print(series_index)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# Data Frame creation
# create a DataFrame from a dictionary of lists
data = {
    "Name": ["Peter Pakar", "Tony Stark", "Bruce Wayne"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}
df = pd.DataFrame(data)
print(df)

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

0    Peter Pakar
1     Tony Stark
2    Bruce Wayne
Name: Name, dtype: str

In [ ]:
# Create A DataFrame from a list of dictionaries
data_list = [
    {"Name": "Peter Pakar", "Age": 25, "City": "New York"},
    {"Name": "Tony Stark", "Age": 30, "City": "Los Angeles"},
    {"Name": "Bruce W ayne", "Age": 35, "City": "Chicago"}
]
df_list = pd.DataFrame(data_list)
print(df_list)

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

In [11]:
df

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

In [ ]:
df["Name"]

0    Peter Pakar
1     Tony Stark
2    Bruce Wayne
Name: Name, dtype: str

In [ ]:
df.loc[0] # Accessing the first row of the DataFrame using .loc

Name    Peter Pakar
Age              25
City       New York
Name: 0, dtype: object

In [25]:
df.iloc[0] # Accessing the first row of the DataFrame using .iloc

Name    Peter Pakar
Age              25
City       New York
Name: 0, dtype: object

In [26]:
df

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

In [27]:
df.at[1, "City"] # Accessing a specific value using .at

'Los Angeles'

In [29]:
# accesing a specific value using .iat
df.iat[2, 2] # Accessing the value in the second row and third column using .iat

'Chicago'

In [30]:
df

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

In [ ]:
df["Age"] = [22,27,32] # Modifying the "Age" column with new values

In [34]:
df

          Name  Age         City
0  Peter Pakar   22     New York
1   Tony Stark   27  Los Angeles
2  Bruce Wayne   32      Chicago

In [35]:
# removing a column
df.drop("City", axis=1, inplace=True) # Removing the "City" column

In [36]:
df

          Name  Age
0  Peter Pakar   22
1   Tony Stark   27
2  Bruce Wayne   32

In [37]:
df["Age"] = df["Age"] + 1 # Incrementing the "Age" column by 1

SyntaxError: invalid syntax (2904145058.py, line 1)

SyntaxError: invalid syntax (3827820173.py, line 1)