In [ ]:
import pandas as pd

In [ ]:
# creating a Series from a list
import pandas as pd
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
# create a DataFrame from a dictionary
data = {"a" :1 , "b": 2, "c": 3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
data2 = [1,2,3,4,5]
index = ['a', 'b', 'c', 'd', 'e']
series_index = pd.Series(data2, index=index)
print(series_index)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# Data Frame creation
# create a DataFrame from a dictionary of lists
data = {
    "Name": ["Peter Pakar", "Tony Stark", "Bruce Wayne"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}
df = pd.DataFrame(data)
print(df)

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

0    Peter Pakar
1     Tony Stark
2    Bruce Wayne
Name: Name, dtype: str

In [ ]:
# Create A DataFrame from a list of dictionaries
data_list = [
    {"Name": "Peter Pakar", "Age": 25, "City": "New York"},
    {"Name": "Tony Stark", "Age": 30, "City": "Los Angeles"},
    {"Name": "Bruce W ayne", "Age": 35, "City": "Chicago"}
]
df_list = pd.DataFrame(data_list)
print(df_list)

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

In [11]:
df

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

In [ ]:
df["Name"]

0    Peter Pakar
1     Tony Stark
2    Bruce Wayne
Name: Name, dtype: str

In [ ]:
df.loc[0] # Accessing the first row of the DataFrame using .loc

Name    Peter Pakar
Age              25
City       New York
Name: 0, dtype: object

In [25]:
df.iloc[0] # Accessing the first row of the DataFrame using .iloc

Name    Peter Pakar
Age              25
City       New York
Name: 0, dtype: object

In [26]:
df

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

In [27]:
df.at[1, "City"] # Accessing a specific value using .at

'Los Angeles'

In [29]:
# accesing a specific value using .iat
df.iat[2, 2] # Accessing the value in the second row and third column using .iat

'Chicago'

In [30]:
df

          Name  Age         City
0  Peter Pakar   25     New York
1   Tony Stark   30  Los Angeles
2  Bruce Wayne   35      Chicago

In [ ]:
df["Age"] = [22,27,32] # Modifying the "Age" column with new values

In [35]:
# removing a column
df.drop("City", axis=1, inplace=True) # Removing the "City" column

In [36]:
df

          Name  Age
0  Peter Pakar   22
1   Tony Stark   27
2  Bruce Wayne   32

In [37]:
df["Age"] = df["Age"] + 1 # Incrementing the "Age" column by 1

In [6]:
data = pd.read_csv("data.csv") # Reading a CSV file into a DataFrame
df = pd.DataFrame(data) # Creating a DataFrame from the read CSV data
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [13]:
df.head(5) # Displaying the first few rows of the DataFrame

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [17]:
data = pd.read_csv("data.csv") # Reading a CSV file into a DataFrame
df = pd.DataFrame(data) # Creating a DataFrame from the read CSV data
df.tail(5) # Displaying the last few rows of the DataFrame

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [15]:
df.describe() # Generating descriptive statistics of the DataFrame

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [18]:
df.dtypes # Displaying the data types of each column in the DataFrame

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

In [19]:
df.isnull() # Checking for null values in the DataFrame

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [23]:
df.isnull().any() # Checking if any column contains null values

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [24]:
df.isnull().sum() # Counting the number of null values in each column

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [26]:
df.fillna(0) # Filling null values with 0 in the DataFrame

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [28]:
df = df.rename(columns = {"Date" : "Sales date"})   # Renaming the "date" column to "Sales date"
df.head()

   Sales date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [41]:
# Change the data type 

df['value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int) # Changing the data type of the "Value" column to float

df.head() # Displaying the first 5 rows of the DataFrame

  Sales date Category  Value   Product  Sales Region  value_new
0 2023-01-01        A   28.0  Product1  754.0   East         28
1 2023-01-02        B   39.0  Product3  110.0  North         39
2 2023-01-03        C   32.0  Product2  398.0   East         32
3 2023-01-04        B    8.0  Product1  522.0   East          8
4 2023-01-05        B   26.0  Product3  869.0  North         26

In [45]:
df['new_values'] = df["Value"].apply(lambda x: x * 2) # Applying a lambda function to double the values in the "Value" column and creating a new column "new_values"
df.head() # Displaying the first 5 rows of the DataFrame

  Sales date Category  Value   Product  Sales Region  value_new  new_values
0 2023-01-01        A   28.0  Product1  754.0   East         28        56.0
1 2023-01-02        B   39.0  Product3  110.0  North         39        78.0
2 2023-01-03        C   32.0  Product2  398.0   East         32        64.0
3 2023-01-04        B    8.0  Product1  522.0   East          8        16.0
4 2023-01-05        B   26.0  Product3  869.0  North         26        52.0

In [46]:
# data Aggregating And Grouping 
df.head()

  Sales date Category  Value   Product  Sales Region  value_new  new_values
0 2023-01-01        A   28.0  Product1  754.0   East         28        56.0
1 2023-01-02        B   39.0  Product3  110.0  North         39        78.0
2 2023-01-03        C   32.0  Product2  398.0   East         32        64.0
3 2023-01-04        B    8.0  Product1  522.0   East          8        16.0
4 2023-01-05        B   26.0  Product3  869.0  North         26        52.0

In [50]:
grouped_mean = df.groupby("Product")["Value"].mean() # Grouping the DataFrame by "Category" and calculating the mean of the "Value" column for each group
print(grouped_mean)

Product
Product1    40.437500
Product2    52.800000
Product3    52.263158
Name: Value, dtype: float64

In [52]:
grouped_sum = df.groupby(["Product", "Region"])["Value"].sum() # Grouping the DataFrame by "Category" and calculating the sum of the "Value" column for each group
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [55]:
grouped_mean = df.groupby(["Product", "Region"])["Value"].mean() # Grouping the DataFrame by "Category" and calculating the sum of the "Value" column for each group
grouped_mean

Product   Region
Product1  East      41.714286
          North      3.000000
          South     50.000000
          West      61.500000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     33.833333
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [58]:
# Aggregating multiple functions
grouped_agg = df.groupby("Product")["Value"].agg(["mean", "sum", "count"]) # Grouping the DataFrame by "Category" and applying multiple aggregation functions (mean, sum, count) to the "Value" column
grouped_agg

               mean    sum  count
Product
Product1  40.437500  647.0     16
Product2  52.800000  792.0     15
Product3  52.263158  993.0     19

In [65]:
# Merging And joining  DataFrames
# create sample DataFrames
df1 = pd.DataFrame({'key' : ['A', 'B', 'C'], 'value1': [1, 2, 3]})
df2 = pd.DataFrame({'key' : ['A', 'B', 'D'], 'value2': [4, 5, 6]})

In [67]:
df1

  key  value1
0   A       1
1   B       2
2   C       3

In [68]:
df2

  key  value2
0   A       4
1   B       5
2   D       6

In [69]:
# Merging DataFrames on the key column
merged_df = pd.merge(df1, df2, on='key', how='inner')
merged_df

  key  value1  value2
0   A       1       4
1   B       2       5

In [71]:
merged_df = pd.merge(df1, df2, on='key', how='outer')
merged_df

  key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [72]:
merged_df = pd.merge(df1, df2, on='key', how='left')
merged_df

  key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [73]:
merged_df = pd.merge(df1, df2, on='key', how='right')
merged_df

  key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [6]:
import pandas as pd
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None) # Reading a CSV file from a URL into a DataFrame

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [8]:
df.to_csv("wine_data.csv", index=False) # Saving the DataFrame to a CSV file without the index

In [14]:
!pip install lxml
!pip install html5lib

Requirement already satisfied: lxml in /Users/abhishekkumar/Data Analyst/venv/lib/python3.13/site-packages (6.0.2)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in /Users/abhishekkumar/Data Analyst/venv/lib/python3.13/site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5lib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [html5lib]
Successfully installed html5lib-1.1 webencodings-0.5.1

In [15]:
import pandas as pd

url = "https://www.fdic.gov/bank-failures/failed-bank-list"
df = pd.read_html(url)

In [17]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [ ]:
hkdsjbkvsdshbdj